export const toefl = [
  ['abroad', 'to or in another country', 'overseas, insternationally'],
  ['abrupt', 'quick; without warning', 'sudden'],
  ['acceptable', 'allowable or satisfactory', 'permissable'],
  ['acclaim', 'enthusiastic approval; applause', 'praise'],
  ['actually', 'being in existence, real or factual', 'truly'],
  ['adverse', 'displeasing, objectionable, or bad', 'unfavorable'],
  ['advice', 'recommendation by someone', 'suggestion'],
  ['attractive', 'calling attention to; pleasing; pretty', 'appealing'],
  ['autonomous', 'by itself; with association', 'independant'],
  ['disapproval', 'the action of disagreeing; not giving approval', 'objection'],
  ['disruptive', 'causing confusion and interruption', 'disturbing'],
  ['haphazardly', 'having no order or pattern; by chance', 'arbitrarily; carelessly'],
  ['persistent', 'continuous; refusing to give up; firm in action or decision', 'constant'],
  ['valid', 'producing a desired result based on truths or facts', 'convincing'],
  ['withdraw', 'to remove. take out, or take back', 'extract'],
  ['advantage', 'something that may help one to be successful or to gain something', 'benefit'],
  ['advent', 'the coming or appearance of something', 'arrival'],
  ['agile', 'able to move in a quick and easy way', 'nimble'],
  ['albeit', 'in spite of the facts, regardless of the fact', 'although'],
  ['appealling', 'attractive or interesting', 'alluring'],
  ['celebrated', 'acclaimed; well-known and popular', 'renowned'],
  ['collide', 'to hit one object against another with violence force; to be in opposition', 'crash'],
  ['contemporary', 'modern, up-to-date, or a person living at the same time as another person', 'current'],
  ['distribute', 'to divide among people or to give out', 'dispense'],
  ['encourage', 'to promote, help or support', 'stimulate'],
  ['energetic', 'full of life, action, or power', 'vigorous'],
  ['frail', 'weak in health or in body', 'fragile'],
  ['myth', 'an invented story or idea', 'legend'],
  ['refine', 'to make pure; to improve', 'perfect'],
  ['worthwhile', 'value in doing something', 'rewarding'],
  ['alter', 'to change or make different', 'modify'],
  ['analyze', 'to study something carefully; to seperate into parts for study', 'examine'],
  ['ancient', 'something from long time ago; very old', 'old'],
  ['annoying', 'a slight bother; disturbing to a person', 'bothersome'],
  ['anticipate', 'to think about or prepare for something', 'predict'],
  ['conform', 'to follow established rules or patterns of behavior', 'adapt'],
  ['enrich', 'to make rich; to make something of greater value', 'enhance'],
  ['intensify', 'to make stronger in feeling or quality', 'heighten'],
  ['intolerable', 'difficult or painful to experience; not able to accept different ways of thought or behavior', 'unbearable'],
  ['ongoing', 'continuing', 'current'],
  ['potential', 'an ability, happening or oppotunity that has not occured or been developed', 'possibility'],
  ['propose', 'to suggest or plan  to do something', 'suggest'],
  ['restore', 'to give back or being back something; to return to the original condition', 'revitalize'],
  ['turbulent', 'to be in a disordered, distributed or unstable condition', 'chaotic'],
  ['vital', 'of great importance; full of life', 'indispensable'],
  ['ambiguous', 'to unclear meaning; something that can be understood in more than one way', 'vague'],
  ['arbitrary', 'an action or decision made with little thought, order or reason', 'haphazard'],
  ['assert', 'to express or defened oneself strongly; to state positevely', 'to declare'],
  ['astounding', 'very surprising', 'astonishing'],
  ['astute', 'very intelligent, smart, clever', 'perceptive'],
  ['concur', 'to have the same opinion or draw the same conclusion', 'agree'],
  ['deceptively', 'making something appear true or good when it is false or bad', 'misleadingly'],
  ['designate', 'to specify, name, or select to do a task; to indicate', 'assign'],
  ['determined', 'strong in one\'s opinion, firm in convention to find out', 'resolute'],
  ['elicit', 'to get the fact or draw out the truth', 'extract'],
  ['instigate', 'to cause a conflict or argument', 'initiate'],
  ['petition', 'to make a request', 'appeal'],
  ['relinquish', 'to give up control', 'abdicate'],
  ['resilient', 'strong enough to recover from difficulty or disease', 'tenacious'],
  ['tempt', 'to make it attractive to do something usually something not good', 'entice'],
  ['baffle', 'to confuse to a point at which no progress can be made', 'puzzle'],
  ['bear', 'to produce, to carry; to show; to endure', 'yeild'],
  ['blur', 'to make something difficult to see', 'cloud'],
  ['brilliant', 'intesify bright or colorful; intelligent', 'radiant'],
  ['caution', 'to alert someone of danger, warn someone to take care or pay attention to something', 'warn'],
  ['delicate', 'needing careful treatment; sensitive, easily broken', 'fragile'],
  ['enhance', 'to increase in a positive way, such as in value, power, or beauty', 'strengthen'],
  ['incessant', 'nonstop, continual, or never-ending', 'constant'],
  ['in conjunction with', 'in addition to, alongside', 'along with'],
  ['intrigue', 'to interest greatly', 'fascinate'],
  ['obstruct', 'to prevent movement, progress, or success', 'block'],
  ['persuade', 'to change a belief or behavior by argument or reason', 'convince'],
  ['shed', 'to throw off natually; to give out', 'discard'],
  ['unique', 'to be only one of a kind; special', 'rare'],
  ['well-suited', 'to be complementary or appropriate; a good match', 'compatible'],
  ['chiefly', 'the most important, the most common', 'mostly'],
  ['coarse', 'not fine or smooth; not delicate', 'rough'],
  ['commonplace', 'ordinary', 'frequent'],
  ['comparatively', 'being measured or judged by comparison', 'relatively'],
  ['complex', 'difficult to understand or explain; having many parts', 'complicated'],
  ['conventional', 'following accepted rules or standards', 'traditional'],
  ['curious', 'odd or strange; eager to learn', 'peculiar'],
  ['emit', 'to send out; give off', 'release'],
  ['exceedingly', 'very; to an unusuall degree', 'extremely'],
  ['exclusively', 'no one else; nothing else; not shared with others', 'restrictively'],
  ['immense', 'extremely large', 'massive'],
  ['rigid', 'not easy to bend; firm; inflexible', 'stuff'],
  ['routinely', 'regularly; usually done', 'ordinarily'],
  ['sufficiently', 'enough; in a satisfying manner', 'adequately'],
  ['visibly', 'can be seen, power of imagination or wisdom', 'noticeably'],
  ['attribute', 'something that is thought to belong to a person or thing', 'characteristic'],
  ['clarify', 'to make more easily understood; to make clear', 'explain'],
  ['conceal', 'to prevent from being seen or discovered', 'hide'],
  ['confirm', 'to make certain; give support', 'prove'],
  ['convenient', 'easy to reach; near; suitable to one\' needs', 'practical'],
  ['core', 'the central or most important part', 'chief'],
  ['critical', 'very serious or unsafe; finding fault', 'dangerous'],
  ['distort', 'to change from the original shape or condition, usually in an unnatural way', 'deform'],
  ['diverse', 'various; distinct from others', 'different'],
  ['eventually', 'to happen at some time in the future, usually gradually', 'finally'],
  ['prosperous', 'successful, wealthy', 'thriving'],
  ['purposefully', 'done for special reason', 'deliberately'],
  ['reveal', 'to uncover; to expose', 'disclose'],
  ['scarcely', 'almost not', 'hardly'],
  ['theoretically', 'according to a reasoned, but not proven point of view'],
  ['accelerate', 'to go faster', 'hasten'],
  ['creep', 'to move slowly and quitely close to the ground; to begin to happen', 'crawl'],
  ['crush', 'to press together so as to completely distort the shape or nature of the object', 'grind'],
  ['cultivate', 'to plant and rise a crop; to encourage growth of a relationship or friendship', 'grow'],
  ['dictate', 'to state demands with the power to enforce', 'impose'],
  ['distinguish', 'to hear, see, or recognize diffrences', 'discriminate'],
  ['engender', 'to cause something new to exist; to create', 'produce'],
  ['engross', 'to become completely occupied or involved in an activity', 'engage'],
  ['flaw', 'a small sign of damage that makes an item imperfect', 'defect'],
  ['harvest', 'the act of collecting a crop; the crops gathered', 'gather'],
  ['mirror', 'to show, as in mirror', 'reflect'],
  ['obtain', 'to gain or secure something', 'gain'],
  ['particle', 'a very small peice of something', 'fragment'],
  ['settle', 'to establish a home; to resolve a disagreement', 'colonize'],
  ['transport', 'to move from one place to another', 'carry'],
  ['accurate', 'careful and exact', 'precise'],
  ['classify', 'to place into groups according to type', 'arrange'],
  ['currency', 'monetary unit; cash', 'money'],
  ['deep', 'far below the surface; complete', 'thorough'],
  ['dense', 'closely packed or crowded; difficult to see through', 'thick'],
  ['dim', 'not bright or clear', 'faint'],
  ['display', 'to show; reveal', 'exhibit'],
  ['exports', 'products sold abroad', 'foreign sales'],
  ['gigantic', 'very large', 'enormous'],
  ['impressive', 'causing admiration because of an object\'s importance, size, or quality', 'imposing'],
  ['install', 'to set up or create an office; to place in a fixed position', 'established'],
  ['lasting', 'forever; without end', 'enduring'],
  ['straightforward', 'easy to understand; simple; honest', 'uncomplicated'],
  ['uniform', 'every part being the same', 'consistent'],
  ['vibrant', 'lively; powerful; full of action; bright', 'brilliant'],
  ['distinct', 'clearly noticed; different', 'definite'],
  ['dominant', 'primary or principal; having or exercising conrol over something', 'major'],
  ['dormant', 'not growing or producing; asleep', 'inactive'],
  ['drab', 'lacking color; uninteresting, boring', 'colorless'],
  ['dramatic', 'something that captures the imagination; exciting', 'emotional'],
  ['eclectic', 'to select or represent something chosen from many sources or places', 'diverse'],
  ['elaborate', 'something with a large number of parts; full of details', 'complex'],
  ['exceptional', 'unusuall in a positive way', 'phenomenal'],
  ['hazardous', 'very risky, unsafe', 'dangerous'],
  ['minuscule', 'of little consequence; very small', 'tiny'],
  ['prime', 'to make ready; first in importance or in time', 'prepare'],
  ['rudimentary', 'simple; not complex', 'basic'],
  ['skeptical', 'to question the truthfulness of information presented as fact; to not trust', 'unconvinced'],
  ['superficial', 'simple; not deep; near to surface', 'shallow'],
  ['vigorous', 'powerful, full of action', 'strong'],
  ['amenity', 'something that makes life easieror more enjoyable', 'convenience'],
  ['disperse', 'to cause to move in many different directions', 'circulate'],
  ['dwelling', 'where people live', 'house'],
  ['element', 'a part of the whole, environment', 'component'],
  ['elementary', 'simple in structure, easy to do', 'primary'],
  ['eliminate', 'to remove, free oneself of something', 'delete'],
  ['emerge', 'to come into view, or existence', 'appear'],
  ['emphasize', 'to show that something is especially important or exceptional', 'highlight'],
  ['encircle', 'to make a circle around', 'surround'],
  ['erratic', 'no regular pattern in thinking or movement; changeable without reason', 'inconsistent'],
  ['exaggerate', 'to make something more than what it is', 'overstate'],
  ['justify', 'to show to be right or reasonable; to support', 'defend'],
  ['mention', 'to say; relate in written form', 'remark'],
  ['prevalent', 'existing widely or commonly', 'commonplace'],
  ['release', 'to allow to come out; to give freedom', 'free'],
  ['benefit', 'to be useful or helpful', 'assist'],
  ['blind', 'unable to see or understand; to conceal', 'unaware'],
  ['broaden', 'to make larger or greater', 'enlarge'],
  ['burgeon', 'growing at a fast pace', 'thrive'],
  ['conspicuously', 'attracting attention', 'noticeably'],
  ['endorse', 'to express approval', 'support'],
  ['enormous', 'very large', 'tremendous'],
  ['entirely', 'completely, thoroughly'],
  ['erode', 'to wear away; disappear slowly', 'deteriorate'],
  ['evaporate', 'to vanish', 'disappear'],
  ['noteworthy', 'deserving positive recognition or attention', 'remarkable'],
  ['recover', 'to get back; to have something returned'],
  ['reportedly', 'to know by report; unconfirmed; supposedly', 'rumored'],
  ['shift', 'a change in position or direction', 'switch'],
  ['susceptible', 'to be subject to influence; capable of being affected by a person or thing', 'vulnerable'],
  ['crucial', 'of great importance; extremely neccessary', 'critical'],
  ['dignitary', 'a very important or famous person, usually associated with a high position in goverment', 'celebrity'],
  ['elude', 'to escape in a tricky way', 'evade'],
  ['evident', 'easy to see, usually because of some proof', 'apparant'],
  ['exhaust', 'to use completely; to expand all energy; very thoprough', 'deplete'],
  ['extensive', 'large in area or number; to make longer', 'comprehensive'],
  ['face', 'to be in the presence of and oppose','confront'],
  ['facet', 'element or component', 'aspect'],
  ['idol', 'a person or image that is loyally admired or respected', 'hero'],
  ['inaccesible', 'something that cannot be reached or communicated with', 'remote'],
  ['oblivious', 'to be unaware of or forgetfull', 'ignorant'],
  ['obviously', 'in a clear, easy to understand way', 'evidently'],
  ['offensive', 'causing anger; rude; being unpleasent', 'insulting'],
  ['predictably', 'in a way that foretells future events', 'expectedly'],
  ['suitable', 'appropriate; correct; convenient', 'apporopriate'],
  ['ample', 'more than enough', 'sufficient'],
  ['arid', 'being a little rain or water', 'dry'],
  ['avert', 'to stop from occurring; to turn away or aside', 'prevent'],
  ['defy', 'to show little fear or regard for rules or established norms; to challenge'],
  ['dilligent', 'done with persistence and hard work; with attention to details', 'conscientious'],
  ['enact', 'to pass a law', 'legislate'],
  ['feign', 'to pretend; make believe', 'stimulate'],
  ['fertile', 'able to produce abundantly', 'rich'],
  ['freshly', 'caught or produced not long ago', 'recently'],
  ['function', 'the normal purpose of something', 'role'],
  ['fundamental', 'a primary or basic element', 'essentianl'],
  ['indiscriminate', 'not chosen carefully; unplanned', 'arbitrary'],
  ['selective', 'carefully chosen', 'discriminating'],
  ['spacious', 'having a lot of room', 'expensive'],
  ['withstand', 'to fight without surrender, to persist', 'survive'],
  ['durable', 'somthing that last a long time', 'sturdy'],
  ['foster', 'to promote growth or development', 'stimulate'],
  ['gain', 'to obtain something needed or useful; to increase to the amount of something', 'attain'],
  ['halt', 'to stop or discontinue', 'stop'],
  ['handle', 'to deal with or control', 'manage'],
  ['harbor', 'to give protection; to not express a desire or opinion; usually bad'],
  ['harmful', 'something that causes pain or damage', 'unhealthy'],
  ['insignificant', 'not important; of little value', 'meaningless'],
  ['mysterious', 'not easily understood or figured out', 'baffling'],
  ['perilous', 'threatening or risky; harmful', 'dangerous'],
  ['promote', 'to encourage or advertise; to elevate in rank or grade', 'boost'],
  ['redundant', 'being excessive; showing unneccessary repetition', 'repetitious'],
  ['reject', 'to refuse', 'refuse'],
  ['substantial', 'important; strongly made; of value', 'significant'],
  ['trait', 'specific qualities that distinguish one from another', 'characteristic'],
  ['conscientious', ''],
  ['convey', ''],
  ['encompass', ''],
  ['expansion', ''],
  ['heighten', ''],
  ['highlight', ''],
  ['inadvertently', ''],
  ['inevitable', ''],
  ['infancy', ''],
  ['mimic', ''],
  ['retrieve', ''],
  ['systematically', ''],
  ['unlikely', ''],
  ['unwarranted', ''],
  ['zenith', ''],
  ['agitate', ''],
  ['confidential', ''],
  ['delighted', ''],
  ['discreetly', ''],
  ['documented', ''],
  ['evoke', ''],
  ['gradually', ''],
  ['impartiall', ''],
  ['inordinate', ''],
  ['instantly', ''],
  ['intentionally', ''],
  ['intrinsic', ''],
  ['inundate', ''],
  ['nominal', ''],
  ['presumably', ''],
  ['absurd', ''],
  ['allocation', ''],
  ['balanced', ''],
  ['come across', ''],
  ['culminate', ''],
  ['fallacious', ''],
  ['feasible', ''],
  ['lack', ''],
  ['limber', ''],
  ['means', ''],
  ['narrow', ''],
  ['preconception', ''],
  ['robust', ''],
  ['steady', ''],
  ['swift', ''],
  ['antiquated', ''],
  ['coherrent', ''],
  ['evolve', ''],
  ['fabricate', ''],
  ['investigation', ''],
  ['normally', ''],
  ['notion', ''],
  ['novel', ''],
  ['opposition', ''],
  ['relate', ''],
  ['suspect', ''],
  ['transform', ''],
  ['trigger', ''],
  ['unbiased', ''],
  ['varied', ''],
  ['accentuate', ''],
  ['disguise', ''],
  ['indifferent', ''],
  ['initiate', ''],
  ['innovative', ''],
  ['narrate', ''],
  ['nevertheless', ''],
  ['obsolete', ''],
  ['omit', ''],
  ['outlandish', ''],
  ['overcome', ''],
  ['partially', ''],
  ['pass', ''],
  ['portray', ''],
  ['streamline', ''],
  ['decline', ''],
  ['gather', ''],
  ['motion', ''],
  ['partisan', ''],
  ['phenomena', ''],
  ['philanthropic', ''],
  ['placid', ''],
  ['plentiful', ''],
  ['reaction', ''],
  ['rhythm', ''],
  ['scenic', ''],
  ['shallow', ''],
  ['sheltered', ''],
  ['vanishing', ''],
  ['account', ''],
  ['archaic', ''],
  ['enlighten', ''],
  ['hasten', ''],
  ['hue', ''],
  ['inactive', ''],
  ['intricate', ''],
  ['magnitude', ''],
  ['oblige', ''],
  ['overlook', ''],
  ['poll', ''],
  ['practical', ''],
  ['predominant', ''],
  ['prompt', ''],
  ['provoke', ''],
  ['analogous', ''],
  ['approximately', ''],
  ['compel', ''],
  ['formidable', ''],
  ['intrusive', ''],
  ['periodic', ''],
  ['prone', ''],
  ['prophetic', ''],
  ['proportions', ''],
  ['readily', ''],
  ['reliably', ''],
  ['reluctantly', ''],
  ['renown', ''],
  ['revive', ''],
  ['triumph', ''],
  ['affordable', ''],
  ['contaminated', ''],
  ['discernible', ''],
  ['flourishing', ''],
  ['maintain', ''],
  ['mediocre', ''],
  ['negligible', ''],
  ['parallel', ''],
  ['peculiar', ''],
  ['potent', ''],
  ['remarkable', ''],
  ['scattered', ''],
  ['solid', ''],
  ['somewhat', ''],
  ['tedious', ''],
  ['briefly', ''],
  ['circulate', ''],
  ['consistently', ''],
  ['exhibit', ''],
  ['found', ''],
  ['improperly', ''],
  ['impulsively', ''],
  ['infrequently', ''],
  ['isolated', ''],
  ['overtly', ''],
  ['profoundly', ''],
  ['sharply', ''],
  ['situated', ''],
  ['subsequently', ''],
  ['unmistakable', ''],
  ['chaotic', ''],
  ['controversial', ''],
  ['exemplify', ''],
  ['gratifying', ''],
  ['interpret', ''],
  ['launch', ''],
  ['legitimate', ''],
  ['lethargy', ''],
  ['particular', ''],
  ['radiant', ''],
  ['ridge', ''],
  ['span', ''],
  ['spontaneous', ''],
  ['stream', ''],
  ['striking', ''],
  ['aptly', ''],
  ['demonstration', ''],
  ['ingredients', ''],
  ['involuntarily', ''],
  ['marvel', ''],
  ['moderate', ''],
  ['motivate', ''],
  ['odd', ''],
  ['profuse', ''],
  ['reflection', ''],
  ['supposedly', ''],
  ['sustained', ''],
  ['symbols', ''],
  ['synthesis', ''],
  ['tangible', ''],
  ['aggravating', ''],
  ['amusement', ''],
  ['conceivably', ''],
  ['convert', ''],
  ['curative', ''],
  ['debilitating', ''],
  ['deplete', ''],
  ['finite', ''],
  ['perceive', ''],
  ['security', ''],
  ['toxic', ''],
  ['tranquility', ''],
  ['trap', ''],
  ['undeniably', ''],
  ['underestimated', ''],
  ['acknowledge', ''],
  ['acquire', ''],
  ['assimilate', ''],
  ['assortment', ''],
  ['caliber', ''],
  ['condensed', ''],
  ['contradictory', ''],
  ['disregarded', ''],
  ['precious', ''],
  ['prominent', ''],
  ['requisite', ''],
  ['unraval', ''],
  ['vague', ''],
  ['vast', ''],
  ['volume', ''],
  ['charisma', ''],
  ['clever', ''],
  ['convince', ''],
  ['endure', ''],
  ['forfeit', ''],
  ['precarious', ''],
  ['severe', ''],
  ['sporadic', ''],
  ['superior', ''],
  ['wanton', ''],
  ['weak', ''],
  ['widespread', ''],
  ['wisdom', ''],
  ['witticism', ''],
  ['woo', ''],
]
