export const toefl = [
  ['abroad', 'to or in another country', 'overseas, insternationally'],
  ['abrupt', 'quick; without warning', 'sudden'],
  ['acceptable', 'allowable or satisfactory', 'permissable'],
  ['acclaim', 'enthusiastic approval; applause', 'praise'],
  ['actually', 'being in existence, real or factual', 'truly'],
  ['adverse', 'displeasing, objectionable, or bad', 'unfavorable'],
  ['advice', 'recommendation by someone', 'suggestion'],
  ['attractive', 'calling attention to; pleasing; pretty', 'appealing'],
  ['autonomous', 'by itself; with association', 'independant'],
  ['disapproval', 'the action of disagreeing; not giving approval', 'objection'],
  ['disruptive', 'causing confusion and interruption', 'disturbing'],
  ['haphazardly', 'having no order or pattern; by chance', 'arbitrarily; carelessly'],
  ['persistent', 'continuous; refusing to give up; firm in action or decision', 'constant'],
  ['valid', 'producing a desired result based on truths or facts', 'convincing'],
  ['withdraw', 'to remove. take out, or take back', 'extract'],
  ['advantage', 'something that may help one to be successful or to gain something', 'benefit'],
  ['advent', 'the coming or appearance of something', 'arrival'],
  ['agile', 'able to move in a quick and easy way', 'nimble'],
  ['albeit', 'in spite of the facts, regardless of the fact', 'although'],
  ['appealling', 'attractive or interesting', 'alluring'],
  ['celebrated', 'acclaimed; well-known and popular', 'renowned'],
  ['collide', 'to hit one object against another with violence force; to be in opposition', 'crash'],
  ['contemporary', 'modern, up-to-date, or a person living at the same time as another person', 'current'],
  ['distribute', 'to divide among people or to give out', 'dispense'],
  ['encourage', 'to promote, help or support', 'stimulate'],
  ['energetic', 'full of life, action, or power', 'vigorous'],
  ['frail', 'weak in health or in body', 'fragile'],
  ['myth', 'an invented story or idea', 'legend'],
  ['refine', 'to make pure; to improve', 'perfect'],
  ['worthwhile', 'value in doing something', 'rewarding'],
  ['alter', 'to change or make different', 'modify'],
  ['analyze', 'to study something carefully; to seperate into parts for study', 'examine'],
  ['ancient', 'something from long time ago; very old', 'old'],
  ['annoying', 'a slight bother; disturbing to a person', 'bothersome'],
  ['anticipate', 'to think about or prepare for something', 'predict'],
  ['conform', 'to follow established rules or patterns of behavior', 'adapt'],
  ['enrich', 'to make rich; to make something of greater value', 'enhance'],
  ['intensify', 'to make stronger in feeling or quality', 'heighten'],
  ['intolerable', 'difficult or painful to experience; not able to accept different ways of thought or behavior', 'unbearable'],
  ['ongoing', 'continuing', 'current'],
  ['potential', 'an ability, happening or oppotunity that has not occured or been developed', 'possibility'],
  ['propose', 'to suggest or plan  to do something', 'suggest'],
  ['restore', 'to give back or being back something; to return to the original condition', 'revitalize'],
  ['turbulent', 'to be in a disordered, distributed or unstable condition', 'chaotic'],
  ['vital', 'of great importance; full of life', 'indispensable'],
  ['ambiguous', 'to unclear meaning; something that can be understood in more than one way', 'vague'],
  ['arbitrary', 'an action or decision made with little thought, order or reason', 'haphazard'],
  ['assert', 'to express or defened oneself strongly; to state positevely', 'to declare'],
  ['astounding', 'very surprising', 'astonishing'],
  ['astute', 'very intelligent, smart, clever', 'perceptive'],
  ['concur', 'to have the same opinion or draw the same conclusion', 'agree'],
  ['deceptively', 'making something appear true or good when it is false or bad', 'misleadingly'],
  ['designate', 'to specify, name, or select to do a task; to indicate', 'assign'],
  ['determined', 'strong in one\'s opinion, firm in convention to find out', 'resolute'],
  ['elicit', 'to get the fact or draw out the truth', 'extract'],
  ['instigate', 'to cause a conflict or argument', 'initiate'],
  ['petition', 'to make a request', 'appeal'],
  ['relinquish', 'to give up control', 'abdicate'],
  ['resilient', 'strong enough to recover from difficulty or disease', 'tenacious'],
  ['tempt', 'to make it attractive to do something usually something not good', 'entice'],
  ['baffle', 'to confuse to a point at which no progress can be made', 'puzzle'],
  ['bear', 'to produce, to carry; to show; to endure', 'yeild'],
  ['blur', 'to make something difficult to see', 'cloud'],
  ['brilliant', 'intesify bright or colorful; intelligent', 'radiant'],
  ['caution', 'to alert someone of danger, warn someone to take care or pay attention to something', 'warn'],
  ['delicate', 'needing careful treatment; sensitive, easily broken', 'fragile'],
  ['enhance', 'to increase in a positive way, such as in value, power, or beauty', 'strengthen'],
  ['incessant', 'nonstop, continual, or never-ending', 'constant'],
  ['in conjunction with', 'in addition to, alongside', 'along with'],
  ['intrigue', 'to interest greatly', 'fascinate'],
  ['obstruct', 'to prevent movement, progress, or success', 'block'],
  ['persuade', 'to change a belief or behavior by argument or reason', 'convince'],
  ['shed', 'to throw off natually; to give out', 'discard'],
  ['unique', 'to be only one of a kind; special', 'rare'],
  ['well-suited', 'to be complementary or appropriate; a good match', 'compatible'],
  ['chiefly', 'the most important, the most common', 'mostly'],
  ['coarse', 'not fine or smooth; not delicate', 'rough'],
  ['commonplace', 'ordinary', 'frequent'],
  ['comparatively', 'being measured or judged by comparison', 'relatively'],
  ['complex', 'difficult to understand or explain; having many parts', 'complicated'],
  ['conventional', 'following accepted rules or standards', 'traditional'],
  ['curious', 'odd or strange; eager to learn', 'peculiar'],
  ['emit', 'to send out; give off', 'release'],
  ['exceedingly', 'very; to an unusuall degree', 'extremely'],
  ['exclusively', 'no one else; nothing else; not shared with others', 'restrictively'],
  ['immense', 'extremely large', 'massive'],
  ['rigid', 'not easy to bend; firm; inflexible', 'stuff'],
  ['routinely', 'regularly; usually done', 'ordinarily'],
  ['sufficiently', 'enough; in a satisfying manner', 'adequately'],
  ['visibly', 'can be seen, power of imagination or wisdom', 'noticeably'],
  ['attribute', 'something that is thought to belong to a person or thing', 'characteristic'],
  ['clarify', 'to make more easily understood; to make clear', 'explain'],
  ['conceal', 'to prevent from being seen or discovered', 'hide'],
  ['confirm', 'to make certain; give support', 'prove'],
  ['convenient', 'easy to reach; near; suitable to one\' needs', 'practical'],
  ['core', 'the central or most important part', 'chief'],
  ['critical', 'very serious or unsafe; finding fault', 'dangerous'],
  ['distort', 'to change from the original shape or condition, usually in an unnatural way', 'deform'],
  ['diverse', 'various; distinct from others', 'different'],
  ['eventually', 'to happen at some time in the future, usually gradually', 'finally'],
  ['prosperous', 'successful, wealthy', 'thriving'],
  ['purposefully', 'done for special reason', 'deliberately'],
  ['reveal', 'to uncover; to expose', 'disclose'],
  ['scarcely', 'almost not', 'hardly'],
  ['theoretically', 'according to a reasoned, but not proven point of view'],
  ['accelerate', 'to go faster', 'hasten'],
  ['creep', 'to move slowly and quitely close to the ground; to begin to happen', 'crawl'],
  ['crush', 'to press together so as to completely distort the shape or nature of the object', 'grind'],
  ['cultivate', 'to plant and rise a crop; to encourage growth of a relationship or friendship', 'grow'],
  ['dictate', 'to state demands with the power to enforce', 'impose'],
  ['distinguish', 'to hear, see, or recognize diffrences', 'discriminate'],
  ['engender', 'to cause something new to exist; to create', 'produce'],
  ['engross', 'to become completely occupied or involved in an activity', 'engage'],
  ['flaw', 'a small sign of damage that makes an item imperfect', 'defect'],
  ['harvest', 'the act of collecting a crop; the crops gathered', 'gather'],
  ['mirror', 'to show, as in mirror', 'reflect'],
  ['obtain', 'to gain or secure something', 'gain'],
  ['particle', 'a very small peice of something', 'fragment'],
  ['settle', 'to establish a home; to resolve a disagreement', 'colonize'],
  ['transport', 'to move from one place to another', 'carry'],
  ['accurate', ''],
  ['classify', ''],
  ['currency', ''],
  ['deep', ''],
  ['dense', ''],
  ['dim', ''],
  ['display', ''],
  ['exports', ''],
  ['gigantic', ''],
  ['impressive', ''],
  ['install', ''],
  ['lasting', ''],
  ['straightforward', ''],
  ['uniform', ''],
  ['vibrant', ''],
  ['distinct', ''],
  ['dominant', ''],
  ['dormant', ''],
  ['drab', ''],
  ['dramatic', ''],
  ['eclectic', ''],
  ['elaborate', ''],
  ['exceptional', ''],
  ['hazardous', ''],
  ['minuscule', ''],
  ['prime', ''],
  ['rudimentary', ''],
  ['skeptical', ''],
  ['superficial', ''],
  ['vigorous', ''],
  ['amenity', ''],
  ['disperse', ''],
  ['dwelling', ''],
  ['element', ''],
  ['elementary', ''],
  ['eliminate', ''],
  ['emerge', ''],
  ['emphasize', ''],
  ['encircle', ''],
  ['erratic', ''],
  ['exaggerate', ''],
  ['justify', ''],
  ['mention', ''],
  ['prevalent', ''],
  ['release', ''],
  ['benefit', ''],
  ['blind', ''],
  ['broaden', ''],
  ['burgeon', ''],
  ['conspicuously', ''],
  ['endorse', ''],
  ['enormous', ''],
  ['entirely', ''],
  ['erode', ''],
  ['evaporate', ''],
  ['noteworthy', ''],
  ['recover', ''],
  ['reportedly', ''],
  ['shift', ''],
  ['susceptible', ''],
  ['crucial', ''],
  ['dignitary', ''],
  ['elude', ''],
  ['evident', ''],
  ['exhaust', ''],
  ['extensive', ''],
  ['face', ''],
  ['facet', ''],
  ['idol', ''],
  ['inaccesible', ''],
  ['oblivious', ''],
  ['obviously', ''],
  ['offensive', ''],
  ['predictably', ''],
  ['suitable', ''],
  ['ample', ''],
  ['arid', ''],
  ['avert', ''],
  ['defy', ''],
  ['dilligent', ''],
  ['enact', ''],
  ['feign', ''],
  ['fertile', ''],
  ['freshly', ''],
  ['function', ''],
  ['fundamental', ''],
  ['indiscriminate', ''],
  ['selective', ''],
  ['spacious', ''],
  ['withstand', ''],
  ['durable', ''],
  ['foster', ''],
  ['gain', ''],
  ['halt', ''],
  ['handle', ''],
  ['harbor', ''],
  ['harmful', ''],
  ['insignificant', ''],
  ['mysterious', ''],
  ['perilous', ''],
  ['promote', ''],
  ['redundant', ''],
  ['reject', ''],
  ['substantial', ''],
  ['trait', ''],
  ['conscientious', ''],
  ['convey', ''],
  ['encompass', ''],
  ['expansion', ''],
  ['heighten', ''],
  ['highlight', ''],
  ['inadvertently', ''],
  ['inevitable', ''],
  ['infancy', ''],
  ['mimic', ''],
  ['retrieve', ''],
  ['systematically', ''],
  ['unlikely', ''],
  ['unwarranted', ''],
  ['zenith', ''],
  ['agitate', ''],
  ['confidential', ''],
  ['delighted', ''],
  ['discreetly', ''],
  ['documented', ''],
  ['evoke', ''],
  ['gradually', ''],
  ['impartiall', ''],
  ['inordinate', ''],
  ['instantly', ''],
  ['intentionally', ''],
  ['intrinsic', ''],
  ['inundate', ''],
  ['nominal', ''],
  ['presumably', ''],
  ['absurd', ''],
  ['allocation', ''],
  ['balanced', ''],
  ['come across', ''],
  ['culminate', ''],
  ['fallacious', ''],
  ['feasible', ''],
  ['lack', ''],
  ['limber', ''],
  ['means', ''],
  ['narrow', ''],
  ['preconception', ''],
  ['robust', ''],
  ['steady', ''],
  ['swift', ''],
  ['antiquated', ''],
  ['coherrent', ''],
  ['evolve', ''],
  ['fabricate', ''],
  ['investigation', ''],
  ['normally', ''],
  ['notion', ''],
  ['novel', ''],
  ['opposition', ''],
  ['relate', ''],
  ['suspect', ''],
  ['transform', ''],
  ['trigger', ''],
  ['unbiased', ''],
  ['varied', ''],
  ['accentuate', ''],
  ['disguise', ''],
  ['indifferent', ''],
  ['initiate', ''],
  ['innovative', ''],
  ['narrate', ''],
  ['nevertheless', ''],
  ['obsolete', ''],
  ['omit', ''],
  ['outlandish', ''],
  ['overcome', ''],
  ['partially', ''],
  ['pass', ''],
  ['portray', ''],
  ['streamline', ''],
  ['decline', ''],
  ['gather', ''],
  ['motion', ''],
  ['partisan', ''],
  ['phenomena', ''],
  ['philanthropic', ''],
  ['placid', ''],
  ['plentiful', ''],
  ['reaction', ''],
  ['rhythm', ''],
  ['scenic', ''],
  ['shallow', ''],
  ['sheltered', ''],
  ['vanishing', ''],
  ['account', ''],
  ['archaic', ''],
  ['enlighten', ''],
  ['hasten', ''],
  ['hue', ''],
  ['inactive', ''],
  ['intricate', ''],
  ['magnitude', ''],
  ['oblige', ''],
  ['overlook', ''],
  ['poll', ''],
  ['practical', ''],
  ['predominant', ''],
  ['prompt', ''],
  ['provoke', ''],
  ['analogous', ''],
  ['approximately', ''],
  ['compel', ''],
  ['formidable', ''],
  ['intrusive', ''],
  ['periodic', ''],
  ['prone', ''],
  ['prophetic', ''],
  ['proportions', ''],
  ['readily', ''],
  ['reliably', ''],
  ['reluctantly', ''],
  ['renown', ''],
  ['revive', ''],
  ['triumph', ''],
  ['affordable', ''],
  ['contaminated', ''],
  ['discernible', ''],
  ['flourishing', ''],
  ['maintain', ''],
  ['mediocre', ''],
  ['negligible', ''],
  ['parallel', ''],
  ['peculiar', ''],
  ['potent', ''],
  ['remarkable', ''],
  ['scattered', ''],
  ['solid', ''],
  ['somewhat', ''],
  ['tedious', ''],
  ['briefly', ''],
  ['circulate', ''],
  ['consistently', ''],
  ['exhibit', ''],
  ['found', ''],
  ['improperly', ''],
  ['impulsively', ''],
  ['infrequently', ''],
  ['isolated', ''],
  ['overtly', ''],
  ['profoundly', ''],
  ['sharply', ''],
  ['situated', ''],
  ['subsequently', ''],
  ['unmistakable', ''],
  ['chaotic', ''],
  ['controversial', ''],
  ['exemplify', ''],
  ['gratifying', ''],
  ['interpret', ''],
  ['launch', ''],
  ['legitimate', ''],
  ['lethargy', ''],
  ['particular', ''],
  ['radiant', ''],
  ['ridge', ''],
  ['span', ''],
  ['spontaneous', ''],
  ['stream', ''],
  ['striking', ''],
  ['aptly', ''],
  ['demonstration', ''],
  ['ingredients', ''],
  ['involuntarily', ''],
  ['marvel', ''],
  ['moderate', ''],
  ['motivate', ''],
  ['odd', ''],
  ['profuse', ''],
  ['reflection', ''],
  ['supposedly', ''],
  ['sustained', ''],
  ['symbols', ''],
  ['synthesis', ''],
  ['tangible', ''],
  ['aggravating', ''],
  ['amusement', ''],
  ['conceivably', ''],
  ['convert', ''],
  ['curative', ''],
  ['debilitating', ''],
  ['deplete', ''],
  ['finite', ''],
  ['perceive', ''],
  ['security', ''],
  ['toxic', ''],
  ['tranquility', ''],
  ['trap', ''],
  ['undeniably', ''],
  ['underestimated', ''],
  ['acknowledge', ''],
  ['acquire', ''],
  ['assimilate', ''],
  ['assortment', ''],
  ['caliber', ''],
  ['condensed', ''],
  ['contradictory', ''],
  ['disregarded', ''],
  ['precious', ''],
  ['prominent', ''],
  ['requisite', ''],
  ['unraval', ''],
  ['vague', ''],
  ['vast', ''],
  ['volume', ''],
  ['charisma', ''],
  ['clever', ''],
  ['convince', ''],
  ['endure', ''],
  ['forfeit', ''],
  ['precarious', ''],
  ['severe', ''],
  ['sporadic', ''],
  ['superior', ''],
  ['wanton', ''],
  ['weak', ''],
  ['widespread', ''],
  ['wisdom', ''],
  ['witticism', ''],
  ['woo', ''],
]
